apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamicebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi