apiVersion: apps/v1
kind: Deployment # used to achieve high availaibility with zero downtime
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins-label
  namespace: mynamespace
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: label-all
  template:
    metadata:
      name: jenkins
      labels:
        app: label-all
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
